server:
  ssl:
    key-store: keystore.jks
    key-store-password: 78827882
    key-password: 78827882
    enabled: true
  port: 8888
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        highlight_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      #      mode: always
      mode: never
  web:
    resources:
      add-mappings: false
logging:
  level:
    root: info
    com:
      example:
        elemental: debug
#    p6spy: debug

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha